---
title: "Automotive Education and Experience"
---

As summarized on my subpage **Education in Business**, I brliefly mentioned my automotive experience. Having so at the two dealerships that I've worked at has helped me refined my automotive knowledge as well as understanding the anatomy of vehicles. Personally, I have owned about eleven vehicles over the course of 5 years, ranging from Subaru's to Toyota's to Lexus's. For the most part, I've done the majority of the work on my vehicles trying to understand the different variations of engine configurations and transmissions. 

## [Education: Automotive Technology]

I was involved in the automotive program at Rio Hondo Community College for two years, ranging from several classes that involved hands-on work on various vehicles. These classes ranged from different subjects from engine repairs, smog, electrical diagnostics, and brakes. Provided below are several of the classes that I partook in to better understand vehicles and how to address issues and maintenance services.

**Classes Taken:**

- **AUTO 101: Introduction Automotive Service & Repair Under the Hood:** Introductory class to general automotive services for components primarily focused within the engine bay.
- **AUTO 103: Introduction Automotive Service & Repair Under Car :** Introductory class that mainly focuses on the whole chassis (drivetrain, tranmission, suspension components)
- **AUTO 106: Automotive Electrical Tool & Diagnostics** The understanding of eletrical components including wiring harnesses, lights, fuses, modules, etc on a vehicle.
- **AUTO 107: Introduction to Automotive Light Service**  A followup on the underhood and undercar services of a vehicle, including battery and basic electrical service, pre-delivery inspection procedures, and preventative maintenance operations.

---

## [Application Into the Workforce: Puente Hills Toyota]

During my educational journey, I applied some of my knowledge at my former job at **[Puente Hills Toyota]** in the City of Industry, as I was able to see first hand various services, from basic oil changes to engine overhauls, with brief hands on experience on customer vehicles.

**Skills Acquired:**
- **Automotive Knowledge:** Hands-on experience on vehicle services, as well as general knowledge and insight for vehicles and their manufacturers.
- **Tool proficiency:** The understanding of tools and their functions to appropriately assess which tool to utilize for specific services.
- **Vehicle Diagnostics:** Looking for ways and finding the reasons behind underlying issues.
- **Technical problem-solving:** After the diagnostic process, looking for ways to tackle the issue via prior knowledge and data information insight.

---

## [Continuation Into the Workforce: Claremont Toyota]

After being with Puente Hills for roughly a year, I went to work at **[Claremont Toyota]**, which is where I currently work at. After starting off as a service greeter, I began to transition into hybrid work as a service express writer, learning how to write up repair orders for the service department, overlooking multi-point inspections by the technician, checking in the customer for their service and going over the report with the customer. From here my automotive knowledge was utilized by helping customers deeply understand the reason behind certain functions and service intervals, allowing for an overall satisfaction in their service.

---